# Source: https://dzlab.github.io/ml/2020/07/14/spark-kubernetes/
# It's unclear why the steps given on the official operator quick start didn't work.
# It's unclear why I need this file.
# But it works.
apiVersion: v1
kind: Namespace
metadata:
    name: spark-operator
---
apiVersion: v1
kind: Namespace
metadata:
    name: spark-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: spark
    namespace: spark-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: spark-operator-role
    namespace: spark-apps
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
subjects:
    - kind: ServiceAccount
      name: spark
      namespace: spark-apps
